// Code generated by "stringer -type=Level"; DO NOT EDIT.

package logger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DEBUG-1]
	_ = x[INFO-2]
	_ = x[ERROR-3]
}

const _Level_name = "DEBUGINFOERROR"

var _Level_index = [...]uint8{0, 5, 9, 14}

func (i Level) String() string {
	i -= 1
	if i < 0 || i >= Level(len(_Level_index)-1) {
		return "Level(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Level_name[_Level_index[i]:_Level_index[i+1]]
}
