logger:
    file: "./var/log/calendar.log"
    level: DEBUG
db:
    type: postgresql
    dsn: "postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable"
    migrations: "file://./migrations"
    max_idle_connects: 10
    max_open_connects: 10
amqp:
    url: 'amqp://calendar:calendar@0.0.0.0:5673/v_calendar'
    exchange_name: 'calendar'
    queue_name: 'calendar'
