version: '3.8'
services:
  calendar:
    build:
      dockerfile: build/calendar/Dockerfile
      context: .
    environment:
      - CALENDAR_DB_DSN=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      - CALENDAR_DB_MIGRATIONS=file:///etc/calendar/migrations/
      - CALENDAR_LOGGER_FILE=
      - CALENDAR_LOGGER_LEVEL=DEBUG
      - CALENDAR_HTTP_SERVER_PORT=8085
      - CALENDAR_API_SERVER_PORT=8086
      - WAIT_HOSTS=db:5432
    ports:
      - 8085:8085
      - 8086:8086
    depends_on:
      - db
  scheduler:
    build:
      dockerfile: build/calendar-scheduler/Dockerfile
      context: .
    environment:
      - CALENDAR_DB_DSN=postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      - CALENDAR_AMQP_URL=amqp://calendar:calendar@rabbitmq:5672/v_calendar
      - CALENDAR_AMQP_EXCHANGE_NAME=calendar
      - CALENDAR_AMQP_QUEUE_NAME=calendar
      - CALENDAR_LOGGER_FILE=
      - CALENDAR_LOGGER_LEVEL=INFO
      - CALENDAR_SELECT_INTERVAL=5s
      - WAIT_HOSTS=db:5432,rabbitmq:5672
    depends_on:
      - db
      - rabbitmq
      - calendar
  sender:
    build:
      dockerfile: build/calendar-sender/Dockerfile
      context: .
    environment:
      - CALENDAR_AMQP_URL=amqp://calendar:calendar@rabbitmq:5672/v_calendar
      - CALENDAR_AMQP_EXCHANGE_NAME=calendar
      - CALENDAR_AMQP_QUEUE_NAME=calendar
      - CALENDAR_LOGGER_FILE=
      - CALENDAR_LOGGER_LEVEL=INFO
      - CALENDAR_THREADS=3
      - WAIT_HOSTS=rabbitmq:5672
    depends_on:
      - rabbitmq
      - scheduler
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_ERLANG_COOKIE: "SDFDDSFDSFDSFFDFQWF"
      RABBITMQ_DEFAULT_USER: "calendar"
      RABBITMQ_DEFAULT_PASS: "calendar"
      RABBITMQ_DEFAULT_VHOST: "v_calendar"
    ports:
      - 5673:5672
      - 15673:15672
